"""empty message

Revision ID: 27079e94dc7a
Revises: fc9aac12d42e
Create Date: 2017-11-10 21:33:37.462575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27079e94dc7a'
down_revision = 'fc9aac12d42e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_content', sa.Column('title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_content', 'title')
    # ### end Alembic commands ###
