"""empty message

Revision ID: d5ead93fc9d7
Revises: 27079e94dc7a
Create Date: 2017-11-11 01:42:31.631625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5ead93fc9d7'
down_revision = '27079e94dc7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_content', 'content',
                    existing_type=mysql.TEXT(),
                    nullable=True)
    op.alter_column('tbl_content', 'title',
                    existing_type=mysql.VARCHAR(length=100),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_content', 'title',
                    existing_type=mysql.VARCHAR(length=100),
                    nullable=True)
    op.alter_column('tbl_content', 'content',
                    existing_type=mysql.TEXT(),
                    nullable=False)
    # ### end Alembic commands ###
