"""empty message

Revision ID: fc9aac12d42e
Revises: 
Create Date: 2017-11-10 21:20:41.670109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc9aac12d42e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('usertype', sa.Integer(), nullable=False),
    sa.Column('regtime', sa.DateTime(), nullable=True),
    sa.Column('keep1', sa.String(length=100), nullable=True),
    sa.Column('keep2', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_content_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('keep1', sa.String(length=100), nullable=True),
    sa.Column('keep2', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('keep1', sa.String(length=100), nullable=True),
    sa.Column('keep2', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['tbl_content_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_content')
    op.drop_table('tbl_content_type')
    op.drop_table('tbl_user')
    # ### end Alembic commands ###
